version: 2
updates:
 
  # Maintain dependencies for poetry
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    commit-message:
        prefix: "â¬†ï¸ ğŸ¤– Dependencies"

